version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: fk
      POSTGRES_DB: fk
    ports:
      - "5432:5432"

  db-adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"

  mock-data:
    image: frikanalen/toches
    restart: on-failure
    profiles: ['mockdata']
    depends_on: [db]
    environment:
      - DATABASE_URL=postgres://postgres:fk@db/fk
      - FK_API_KEY=1234
    command: [ 'sh', '-c', 'sleep 10s; yarn makeMockData' ]