version: "3.1"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: fk
      POSTGRES_DB: fk
    ports:
      - 5432:5432

  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
